global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['209.38.227.89:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['209.38.227.89:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['209.38.227.89:8080']